---
title: "ENormalize the greenness index"
output: NULL
author: "Jinliang Yang"
date: 03-19-2021
---

## Normalize path
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Normalized data

```{r}
dn <- read.csv("cache/VI_average_fb2019_n46364_ref_ncolor.csv")
dn$date <- as.factor(dn$date)
dn$date <- factor(dn$date, 
                  levels = c("July6", "Aug12", "Aug14", "Aug16", "Aug20", "Aug22", "Aug23", "Aug26", "Aug30",  "Sept1", "Sept3", "Sept5"),
                  labels =c("July 6", "Aug 12", "Aug 14", "Aug 16", "Aug 20", "Aug 22", "Aug 23", "Aug 26", "Aug 30",  "Sept 1", "Sept 3", "Sept 5"))

dn <- subset(dn, !(Genotype.x %in% "Check"))
d1 <- subset(dn, Filter.Type %in% "ExG 131" & Reference.Rep == 1)
fsize=18
```


### Plot the different genotypes


```{r}

library(plyr)
### mean coverage in plus N plots
m1 <- ddply(d1, .(date, Treatment, Pedigree), summarise,
            ExG = mean(ExG2),
            RGB = mean(RGB),
            NGR = mean(NGR),
            GLI = mean(GLI),
            MGR = mean(MGR),
            VARI = mean(VARI),
            VEG = mean(VEG),
            Woebbecke = mean(Woebbecke..abs.))

pn <- subset(m1, Treatment == "Nitrogen")
pn$uid <- paste(pn$date, pn$Pedigree, sep="_")

mn <- subset(m1, Treatment == "No Nitrogen")
mn$uid <- paste(mn$date, mn$Pedigree, sep="_")

m <- merge(pn[,-2], mn[,-1:-3], by="uid")
m$ExG <- m$ExG.x/m$ExG.y
m$RGB <- m$RGB.x/m$RGB.y
m$NGR <- m$NGR.x/m$NGR.y
m$GLI <- m$GLI.x/m$GLI.y
m$MGR <- m$MGR.x/m$MGR.y
m$VARI <- m$VARI.x/m$VARI.y
m$VEG <- m$VEG.x/m$VEG.y
m$Woebbecke <- m$Woebbecke.x/m$Woebbecke.y

```


```{r}
library(ggplot2)
library(tidyr)
fsize=18

i1 <- which(names(m) %in% "ExG")
i2 <- which(names(m) %in% "Woebbecke")
idx <- names(m)[i1:i2]
df1 <- gather(m[, c("date", "Pedigree", idx)], key=VI, value=value, 3:10)

df1 <- subset(df1, value < 5)

p2 <- ggplot(df1, aes(x=date, y=value)) +
  facet_grid(VI ~ ., scales = "free") +
  geom_violin(trim=FALSE, fill="grey") + 
  # geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  geom_boxplot(width=.1, outlier.colour=NA) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  xlab("") +
  ylab( "Ratio of vegetation indices (+N/-N)") +
      geom_hline(yintercept=1, linetype="dashed", 
                color = "red") +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.y = element_text(size = 14, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
p2

```



```{r}
pdf("graphs/VIs_genotypes.pdf", width=12, height = 12)
p2
dev.off()
```













