---
title: "Eric data: VI Average"
output: NULL
author: "Jinliang Yang"
date: 03-03-2021
---

## Normalize path
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


# Vegation Index over time

```{r}
getdf <- function(indir="data/CanopyCoverage/NE"){
  files <- list.files(path=indir, pattern="average", full.names = TRUE)
  df <- data.frame()
  for(i in 1:length(files)){
    tem <- read.csv(files[i], header=T)
    tem$file <- files[i]
    df <- rbind(df, tem)
  }
  df$date <- gsub(".*sat_|.csv|_merged", "", df$file)
  df$date <- factor(df$date,
    levels = c("J6", "Aug12", "Aug14", "Aug16", "Aug20", "Aug22", "Aug23", "Aug26", "Aug30", "Sept1", "Sept3", "Sept5"))
  return(df)
}

#ch1 <- subset(ch, Row.Numbers %in% "1065 and 1066" & Reference.Rep == 1 )

p1 <- getdf(indir="data/VI_Average/NE")
p2 <- getdf(indir="data/VI_Average/NW")
p3 <- getdf(indir="data/VI_Average/SE")
p4 <- getdf(indir="data/VI_Average/SW")

df <- rbind(p1, p2, p3, p4)

df$Row <- gsub(" .*", "", df$Row.Numbers)

fb <- read.csv("data/CRRI_2019_Field_Book_final.csv", header=TRUE)
df0 <- merge(df, fb, by="Row", all.x=TRUE)
df0 <- subset(df0, Reference.Rep == 1)
df0$date <- as.character(df0$date)
df0[df0$date == "J6", ]$date <- "July6"

write.table(df0, "cache/VI_average_fb2019_n46364_ref.csv", sep=",", row.names=FALSE, quote=FALSE)
```



### Check plots

```{r}
df0 <- read.csv("cache/VI_average_fb2019_n46364_ref.csv")

# select check and reference rep
check <- subset(df0, Genotype.x %in% "Check" & Reference.Rep == 1 & Filter.Type %in% "ExG 131")

d1 <- check
```

















#### Plot check plants

```{r}
library(ggplot2)
library(tidyr)

d1$date <- as.factor(d1$date)

idx <- names(d1)[11:20]
df1 <- gather(d1[, c("date", "Treatment", "Rep", idx)], key=VI, value=value, 4:13)


#### Function to get the plots
getplot <- function(vidx){
  fsize=18

dodge <- position_dodge(width = 0.6)
p1 <- ggplot(subset(df1, VI %in% vidx), aes(x=date, y=value)) +
  # facet_grid(VI ~ .) +
  geom_violin(aes(fill = Treatment), position = dodge, trim=FALSE) + 
  geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  scale_fill_manual(values=c("#E69F00", "#56B4E9")) +
  xlab("") +
  ylab("Canopy Coverage (%)") +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
p1
  
}



tb <- as.data.frame(table(df1$VI))

for(i in 1:nrow(tb)){
  vidx <- as.character(tb$Var1[i])
  pdf(paste0("graphs/VI_", vidx, ".pdf"), width=12, height = 6)
  print(getplot(vidx=vidx))
  dev.off()
}

```

















### Plot the different genotypes


```{r}
# select geno and reference rep
geno <- subset(df0, !(Genotype.x %in% "Check") & Reference.Rep == 1)

g1 <- subset(geno, Filter.Type %in% "Custom")
g1$date <- as.character(g1$date)
g1[g1$date == "J6", ]$date <- "July6"

library(plyr)
### mean coverage in plus N plots
m1 <- ddply(g1, .(date, Treatment, Pedigree), summarise,
            mcov = mean(Percent.Cover))
pn <- subset(m1, Treatment == "Nitrogen")
names(pn)[4] <- "mcov_pn"
pn$uid <- paste(pn$date, pn$Pedigree, sep="_")

mn <- subset(m1, Treatment == "No Nitrogen")
names(mn)[4] <- "mcov_mn"
mn$uid <- paste(mn$date, mn$Pedigree, sep="_")

m <- merge(pn[,c(1,3:5)], mn[,4:5], by="uid")
m$ratio <- m$mcov_pn/m$mcov_mn
```


```{r}
fsize=18

m <- subset(m, ratio < 2)
m$date <- as.factor(m$date)

m$date <- factor(m$date, 
                  levels = c("July6", "Aug12", "Aug14", "Aug16", "Aug20", "Aug22", "Aug23", "Aug26", "Aug30",  "Sept1", "Sept3", "Sept5"),
                  labels =c("July 6", "Aug 12", "Aug 14", "Aug 16", "Aug 20", "Aug 22", "Aug 23", "Aug 26", "Aug 30",  "Sept 1", "Sept 3", "Sept 5"))

p2 <- ggplot(m, aes(x=date, y=ratio)) +
  #facet_grid(Filter.Type ~ .) +
  geom_violin(trim=FALSE, fill="grey") + 
  # geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  geom_boxplot(width=.1, outlier.colour=NA) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  xlab("") +
  ylab("Canopy Coverage (+N/-N)") +
      geom_hline(yintercept=1, linetype="dashed", 
                color = "red") +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
p2
```


```{r}
library("cowplot")

# arrange two plots into one column
pdf("graphs/canopy_coverage.pdf", width=12, height = 8)
plot_grid(
  p1, p2,
  labels = c('A', 'B'), label_size = 20, ncol = 1
)
dev.off()
```