---
title: "Eric data: VI Average"
output: NULL
author: "Jinliang Yang"
date: 03-03-2021
---

## Normalize path
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

## Summary of the pvals

```{r}
library(plyr)
leaf <- read.csv("cache/VI_leaf_pvals_n1920_dn.csv")
leaf <- subset(leaf, trait %in% c("LA", "Nitrogen"))
sum1 <- ddply(leaf, .(date, trait), summarise,
             mean_r=mean(cor, na.rm=TRUE),
             med_r=median(cor, na.rm=TRUE))
# Aug12
# Aug26
leaf1 <- subset(leaf, date == "Aug12")

p <- read.csv("cache/VI_pheno_pvals_n480.csv")
p <- subset(p, trait %in% "Weight.of.20.seeds")
sum2 <- ddply(p, .(date, trait), summarise,
             mean_r=mean(cor, na.rm=TRUE),
             med_r=median(cor, na.rm=TRUE))
# Aug23
p1 <- subset(p, date == "Aug30")
```


### Plot correlation overtime
```{r}

df <- rbind(leaf, p)
df <- subset(df, !(type %in% c("ExG", "Woebbecke..no.abs.")))
df$type <- factor(df$type, 
                  levels = c("ExG2", "GLI", "MGR", "NGR", "RGB", "VARI", "VEG", "Woebbecke..abs."),
                  labels = c("ExG", "GLI", "MGR", "NGR", "RGB", "VARI", "VEG", "Woebbecke"))

```

```{r}
library(ggplot2)
library(wesanderson)
fsize=18

df$date <- factor(df$date, 
                  levels = c("July 6", "Aug 12", "Aug 14", "Aug 16", "Aug 20", "Aug 22", "Aug 23", "Aug 26", "Aug 30",  "Sept 1", "Sept 3", "Sept 5"),
                  labels =c("July 6", "Aug 12", "Aug 14", "Aug 16", "Aug 20", "Aug 22", "Aug 23", "Aug 26", "Aug 30",  "Sept 1", "Sept 3", "Sept 5"))

df$trait <- factor(df$trait, 
                  levels = c("Nitrogen", "LA", "Weight.of.20.seeds"),
                  labels =c("Nitrogen", "Leaf Area","20 Kernel Weight"))

p2 <- ggplot(df, aes(x=factor(date), y=abs(cor), group=type, color=type)) +
  facet_grid(trait ~ ., scales = "free", switch="y") +
  geom_line(size=1) +
  # geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  # geom_boxplot(width=.1, outlier.colour=NA) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  #scale_color_manual(values=wes_palette(n=8, name = "Zissou1", type = "continuous"), name = "") +
  geom_vline(xintercept=6, linetype="dashed", size=1.3, color = "grey") +
  xlab("") +
  ylab("Correlation coefficient (|r|)") +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.y = element_text(size = 14, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          axis.text.x = element_text(angle = 45, hjust=1),
          legend.position = "top", 
          legend.title=element_blank(),
          legend.text = element_text(size=fsize-2))
p2

save(file="cache/r_time_series.RData", list=c("p2", "df"))
```










# Vegation Index over time

```{r}
df0 <- read.csv("cache/VI_average_fb2019_n46364_ref_ncolor.csv")

df1 <- subset(df0, Filter.Type %in% "ExG 131")

phenotype <- read.csv("data/pheno2019/2019_yield_traits.csv")
dp <- merge(df1, phenotype, by.x="Row", by.y="row")

dp1 <- subset(dp, date %in% "Aug22")
```


```{r}
library("tidyr")
idx1 <- which(names(dp) == "ExG")
idx2 <- which(names(dp) == "Woebbecke..abs.")

d0 <- dp1[, c("Row", "nitrogen", "Weight.of.20.seeds","cob.length", "cob.weight", "cob.diameter", names(dp)[idx1:idx2])]
d <- gather(d0, key=index, value=value, 7:ncol(d0))

```



```{r}
vari <- subset(d, index %in% "VARI")
vari$value <- vari$value*1000
fit1 <- lm(Weight.of.20.seeds ~ value, data=vari)

pv <- ggplot(vari, aes(x=value, y=Weight.of.20.seeds)) +
  geom_point(aes(color=nitrogen)) +
  # geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  geom_smooth(method = "lm") +
  
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  xlab("VARI") +
  ylab("20 Kernel Weight") +
  scale_color_manual(values=c("#E69F00", "#56B4E9"), name = "",labels = c("+N", "-N")) +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "none", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
pv

save(file="cache/VARI_20kw.RData", list=c("pv", "vari", "fit1"))
```