---
title: "Generate shapefiles"
output: html_notebook
---

## Normalize path
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

```{r}
library(rgdal)

shape <- readOGR(dsn = 'data/contours', layer="contours")

# for shapefiles, first argument of the read/write/info functions is the
# directory location, and the second is the file name without suffix
 
# optionally report shapefile details
ogrInfo(".", "nw-rivers")
# Source: ".", layer: "nw-rivers"
# Driver: ESRI Shapefile number of rows 12 
# Feature type: wkbLineString with 2 dimensions
# +proj=longlat +datum=WGS84 +no_defs  
# Number of fields: 2 
#     name type length typeName
#     1   NAME    4     80   String
#     2 SYSTEM    4     80   String
 
# read in shapefiles
centroids.rg <- readOGR(".", "nw-centroids")
rivers.rg <- readOGR(".", "nw-rivers")
counties.rg <- readOGR(".", "nw-counties")
 
# note that readOGR will read the .prj file if it exists
print(proj4string(counties.rg))
# [1] " +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
 
# generate a simple map showing all three layers
plot(counties.rg, axes=TRUE, border="gray")
points(centroids.rg, pch=20, cex=0.8)
lines(rivers.rg, col="blue", lwd=2.0)
 
# write out a new shapefile (including .prj component)
writeOGR(counties.rg, ".", "counties-rgdal", driver="ESRI Shapefile")
```

