---
title: "Figure3a: VI Average"
output: NULL
author: "Jinliang Yang"
date: 09-03-2021
---

## Normalize path
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('..//')) 
#library(tidyverse)
```


# Vegation Index over time

```{r}
df0 <- read.csv("cache/VI_average_fb2019_n46364_ref_ncolor.csv")

df1 <- subset(df0, Filter.Type %in% "ExG 131")

phenotype <- read.csv("data/pheno2019/2019_yield_traits.csv")
dp <- merge(df1, phenotype, by.x="Row", by.y="row")

dp1 <- subset(dp, date %in% "Aug22")
```


```{r}
library("tidyr")
idx1 <- which(names(dp) == "ExG")
idx2 <- which(names(dp) == "Woebbecke..abs.")

d0 <- dp1[, c("Row", "nitrogen", "Weight.of.20.seeds","cob.length", "cob.weight", "cob.diameter", names(dp)[idx1:idx2])]
d <- gather(d0, key=index, value=value, 7:ncol(d0))

```



```{r}
vari <- subset(d, index %in% "VARI")
vari$value <- vari$value*1000
fit1 <- lm(Weight.of.20.seeds ~ value, data=vari)

pv <- ggplot(vari, aes(x=value, y=Weight.of.20.seeds)) +
  geom_point(aes(color=nitrogen)) +
  # geom_boxplot(aes(group = interaction(date, Treatment)), width=.1, outlier.colour=NA, position = dodge) +
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  geom_smooth(method = "lm") +
  
  # geom_jitter(shape=16, position=position_jitter(0.2), fill=Treatment) + 
  xlab("VARI") +
  ylab("20 Kernel Weight") +
  scale_color_manual(values=c("#E69F00", "#56B4E9"), name = "",labels = c("+N", "-N")) +
  theme_classic() +
  theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "none", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
pv

save(file="cache/VARI_20kw.RData", list=c("pv", "vari", "fit1"))
```